version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '54324:54324'
    environment:
      - POSTGRES_USER=cesul
      - POSTGRES_PASSWORD=cesul
      - POSTGRES_DB=gestortarefa
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data: